name: Feature request
description: Suggest an idea
labels: ["enhancement"]
body:
  - type: textarea
    id: proposal
    attributes:
      label: Proposal
      placeholder: What problem does this solve?
    validations:
      required: true
  - type: input
    id: motivation
    attributes:
      label: Motivation / Use case
