name: Release to PyPI
on:
  push:
    tags:
      - 'v*'
permissions:
  contents: read
  id-token: write
concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - uses: abatilo/actions-poetry@v3
      - name: Install deps
        run: poetry install --no-interaction
      - name: Build package
        run: poetry build
      - name: Twine check
        run: python -m pip install -q twine && twine check dist/*
      - name: Publish to PyPI (token secret)
        uses: pypa/gh-action-pypi-publish@v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
